<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8c69215e-6932-4b0c-872a-262d5adba0d4</testSuiteGuid>
   <testCaseLink>
      <guid>bd59ea50-a0fb-4d01-994e-412fd143991e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>983f5ee9-7780-480f-9362-a6fb447762a3</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>60789ae4-89f9-49a2-8912-d05bd9db1ecd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>edfc9817-6b09-42c7-a9d6-7eb93babfc8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>ce803fff-9f1c-46e7-b553-8b0bd305d29f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>674a98f9-27ea-4b1e-a0e1-13c4d91ad901</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>246b963b-959b-4c8f-b803-bdf0064f4ff2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>3d322768-e39e-4c84-8b51-710a47f2b188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>3ff06a8d-f7a9-484f-a7e7-1a5604faf9ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f5ee9-7780-480f-9362-a6fb447762a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>4bba3c01-351b-4900-bc78-b027f8cadc5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cbaa931-28de-43aa-8ed1-7de3b628ab83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-02-Transaction-AppPending-InputCorporate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5669339-79ca-4f56-b5eb-f5965f7e41ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d904fe2d-fb14-4218-87b7-cae7c91ec023</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a87bc23-9323-45e7-b6e3-eadeebb79d9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1cea696-00a3-4e81-8aee-24b782ec29b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>475c05ce-00fa-4d5f-a767-afc94680e6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2983acaa-7b3a-4bbe-85e0-a9dd6d5655ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910574b7-a250-4f26-9048-2f479cb6e9f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b25e21b5-89ca-4be7-8fcd-d3456cc14644</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75be0b8a-8149-4739-9416-c9ffab813036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb00ccce-5cd7-4307-a3a6-cd49c9f82297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab791b03-97ec-4f0f-86bc-81eeeb1b6f14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee12a5e-bf79-4080-baba-d0859560b4e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3655bad7-b3fd-4d8c-820e-3b973ac66845</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e71e9d8-7f23-4afe-afba-9bc70a8962e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b387ca8-2e4c-47a2-af47-9eea5eb7aaab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>913997ca-c321-4a37-bd50-9fc0da9d3ff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636dcbfa-81ce-40f8-a923-0cd32cf50c9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46059e24-e16f-45af-b704-31e3b1cceb39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f08f574-a3f7-4792-93fd-46bd0da2aae8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b31d946e-b333-4977-afe9-f57b8a4c971e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05b593e0-a4ca-4aa5-95b5-4c5db7867fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e49f04d-f2f9-46d9-b999-9adac1a82e7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a2f1de2-5243-4f13-a1a9-e27959eea5dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0665ee7e-3f0b-4fe1-ad09-f2d0d822984d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9af108ba-9f86-48e8-8818-cc9ab28e3f2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698a12a4-493e-4f09-85e9-e11fdae4a928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c646e4be-2e69-4674-8939-f5ff952e6d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6d9862-d9b3-4fde-b62f-bee325635c8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceb9d2b6-e893-4566-ac8d-44c097f298d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d2c622-6459-4e6c-bbc3-c38ff9f527e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b45ca6e3-3376-4a8f-9211-b333d5c473f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99847996-deca-4df3-b842-0b2f9e187387</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>169f8b93-d485-4924-aa50-f570e07a483f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>324d82e2-a2ed-44ff-a49e-f35702fa09f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47528c01-143d-4ca1-a6f8-5050a7d775a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36fe33c4-3691-499a-bfe6-35b337016e2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e81bb8-0d1f-4a8a-97ff-f2f6a9aa6818</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4023b7ed-909c-4a4b-beef-a3b7247fb488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0601450-b302-4197-8d41-9054556af021</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ae883f-8d05-4537-bcf4-0492ce73d514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>042e55dd-3d82-40e2-b5d3-ef5f41272c2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8415121e-e8d9-4b3e-8e0e-bdb1fbf5cacc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3106b2a-a7de-4886-8947-54dfd5af4b2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21820a8-eeae-4cda-93db-635aba0c0bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28f1a0c2-900c-4dae-ad6b-f21639d0b2f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e310205e-1d66-431c-86eb-15973ef4b741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06af43f5-593a-4d6d-a57a-a3cd97f337da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d393c01-8241-43d2-9809-8b2a2f1a50d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be2a6d2e-fc9d-4862-9b49-f3dafe4ef0d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b62116c-cca5-4334-bd37-dc0157c1ad1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d32fad-c641-4e17-9931-a0283099d41b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72eef85-a5a6-433e-b1fc-d3fab60ce3a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35de837-1716-4fa5-9a6f-ddb3753b3674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e02cee-44bd-4958-ae86-e7ba7e5508ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e14cc692-e296-4352-8bd0-b200be07e490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e455cfd7-c11a-4d15-bba0-d6467b4dd956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c63c451-8883-4327-8918-37ce6be615cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c952084d-fdd3-401a-9bef-8fa8f1731ed2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4122edd1-fad9-4f38-9479-77c764e59266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6277fbf-363c-4efe-b7cc-e423f74135b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26034611-d58c-4dfa-a18e-7f300d95b9cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ab07094-f59b-4ff0-b25b-552dafc71be3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0919500-0f67-48ae-81fa-a3564287af75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f8dd6de-6870-4155-8de1-236709aaffdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a66905a-58b4-40bd-8373-20617ca3a41d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47cb9dab-3988-44f7-b2ed-d9bb2ac13aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbc84ea-38da-4818-afea-bbf2815fcae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4becda4-c675-41b6-8c3b-6f205003faa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1488665-b469-48ad-b256-dfbd50dacb8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83474069-e750-432e-aa10-f2408e5a3746</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
