<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account No. 10 Digit_inline-checkbox-autodebetNoRek</name>
   <tag></tag>
   <elementGuidId>76cd5149-15e0-4998-83fa-bcf93116cb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inline-checkbox-autodebetNoRek']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'inline-checkbox-autodebetNoRek']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inline-checkbox-autodebetNoRek</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f833f2af-f1ed-45da-9797-2a19234bdf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>autodebetNoRek</value>
      <webElementGuid>5f987063-aa93-4ed0-be86-9403dfc5f9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inline-checkbox-autodebetNoRek</value>
      <webElementGuid>87f826c2-bc99-46b8-82ee-33c7c5207541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>436342fe-11a1-4be4-be4e-589cbfe51284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-touched ng-dirty ng-valid</value>
      <webElementGuid>70c85b36-4a10-4aa4-bb0c-bc5c4967e850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inline-checkbox-autodebetNoRek&quot;)</value>
      <webElementGuid>30396383-3fa3-4257-8191-ad0f3872bbf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inline-checkbox-autodebetNoRek']</value>
      <webElementGuid>b74a92a2-e4d1-46c4-b826-fcf37b9d0044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Payment']/div/div[2]/div/div/input</value>
      <webElementGuid>6a73c3ce-47f8-4b73-a751-ea549d0baa8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>d59f3f3a-c3ac-4838-9f2b-7cb58d0d3bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inline-checkbox-autodebetNoRek' and @type = 'checkbox']</value>
      <webElementGuid>5a6b994b-0952-4f34-8444-d8ea5b1a0f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
