<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_purpose_kedua</name>
   <tag></tag>
   <elementGuidId>2a76d16f-cec8-462a-9d28-1501a5fb3bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data-vehicle-0']/div[2]/div[5]/div/ng-select/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'purpose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.w-100.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-pristine.ng-invalid.ng-select-focused.ng-select-bottom.is-invalid.ng-touched > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31d9f299-44fc-49db-a2aa-1445ae15aaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b8453fd6-3267-4885-a7a9-b7295c0628b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9023506c-e077-4999-8389-383b5e1c7ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bdaabae7-9ecc-42b7-931d-21bdafde1dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea4adfe1-38d2-48ca-8889-32a2e0e86f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a09257749715</value>
      <webElementGuid>01d04386-84af-4cb1-ab85-eef9d6e26628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-vehicle-0&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 form-group&quot;]/div[@class=&quot;input-container d-flex is-invalid&quot;]/ng-select[@class=&quot;w-100 ng-select ng-select-single ng-select-searchable ng-select-clearable ng-pristine ng-invalid ng-select-focused ng-select-bottom is-invalid ng-touched&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>0aecf958-8314-488e-9706-f99ccbb7914b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>purpose</value>
      <webElementGuid>36dd938f-669c-4e8f-8c74-8c10a3c21474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[52]</value>
      <webElementGuid>349a6488-994e-4808-a42a-5638a5aa06d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-vehicle-0']/div[2]/div[5]/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>93ece74d-e3ed-4330-91ea-8743159b0019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>f624eedd-cb82-4100-a087-0b2f8203d57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>31461b41-d4f8-421f-a78a-b75cea3d0186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
