<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_carinsurancebranch_kedua</name>
   <tag></tag>
   <elementGuidId>da970011-0a86-4db8-8f26-de1c24b61e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='insurance-accordion']/div/div[2]/div/div/div/div/div[2]/div/ng-select/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'carInsuranceBranchName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.w-100.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-pristine.ng-invalid.ng-select-bottom.is-invalid.ng-touched.ng-select-focused.ng-select-opened > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42fce744-fd46-4347-b0e1-4cfb38361622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>8d24be49-30a3-4f25-b354-c9496922b145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c170e05e-7e7c-421d-9601-2f682cc38641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7792d13-cb55-4424-86cf-b95e960edd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f3e16b0-d8ec-4ff8-976a-4e46f82e98de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a1cbc4ee12fd</value>
      <webElementGuid>ebd8d91b-7620-481f-99fa-f08e51903118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>a1cbc4ee12fd</value>
      <webElementGuid>12e5db2b-5208-44f7-bc75-1508148a7dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a1cbc4ee12fd-0</value>
      <webElementGuid>6d1b3bce-3564-4e76-8ef5-923c1fcc4423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-accordion&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;row ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card main-car-insurance&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 form-group&quot;]/div[@class=&quot;input-container d-flex is-invalid&quot;]/ng-select[@class=&quot;w-100 ng-select ng-select-single ng-select-searchable ng-select-clearable ng-pristine ng-invalid ng-select-bottom is-invalid ng-touched ng-select-focused ng-select-opened&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>e8fef240-4896-4f41-bfde-8197828e7ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>carInsuranceBranchName</value>
      <webElementGuid>a313343b-6b6e-46ef-9850-efd85b7bbf70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[85]</value>
      <webElementGuid>d060085a-9335-4936-8085-bc75c40d1809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insurance-accordion']/div/div[2]/div/div/div/div/div[2]/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>b108530d-e124-419b-9e86-fd82c459672a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>e41a7ec4-3c75-41ae-9c49-d071beafac62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>cb3d9105-41b2-401b-9a68-f8c376a51a09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
