<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1-S4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>247b59c1-25e6-4a81-b2f3-14fea87985f4</testSuiteGuid>
   <testCaseLink>
      <guid>bc85f157-d961-4f41-8e69-e087a77d7b65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>60789ae4-89f9-49a2-8912-d05bd9db1ecd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>edfc9817-6b09-42c7-a9d6-7eb93babfc8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>ce803fff-9f1c-46e7-b553-8b0bd305d29f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>674a98f9-27ea-4b1e-a0e1-13c4d91ad901</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>246b963b-959b-4c8f-b803-bdf0064f4ff2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>3d322768-e39e-4c84-8b51-710a47f2b188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>3ff06a8d-f7a9-484f-a7e7-1a5604faf9ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2da3bf1-b95b-4819-b79b-34f1bed8c6b1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>4bba3c01-351b-4900-bc78-b027f8cadc5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fa6d0e8-b462-4c77-b2e9-2ff6a3858de0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-02-Transaction-AppPending-InputCorporate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5669339-79ca-4f56-b5eb-f5965f7e41ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d904fe2d-fb14-4218-87b7-cae7c91ec023</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a87bc23-9323-45e7-b6e3-eadeebb79d9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1cea696-00a3-4e81-8aee-24b782ec29b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>475c05ce-00fa-4d5f-a767-afc94680e6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2983acaa-7b3a-4bbe-85e0-a9dd6d5655ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910574b7-a250-4f26-9048-2f479cb6e9f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b25e21b5-89ca-4be7-8fcd-d3456cc14644</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75be0b8a-8149-4739-9416-c9ffab813036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb00ccce-5cd7-4307-a3a6-cd49c9f82297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab791b03-97ec-4f0f-86bc-81eeeb1b6f14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ee12a5e-bf79-4080-baba-d0859560b4e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3655bad7-b3fd-4d8c-820e-3b973ac66845</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e71e9d8-7f23-4afe-afba-9bc70a8962e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b387ca8-2e4c-47a2-af47-9eea5eb7aaab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>913997ca-c321-4a37-bd50-9fc0da9d3ff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636dcbfa-81ce-40f8-a923-0cd32cf50c9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46059e24-e16f-45af-b704-31e3b1cceb39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f08f574-a3f7-4792-93fd-46bd0da2aae8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b31d946e-b333-4977-afe9-f57b8a4c971e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05b593e0-a4ca-4aa5-95b5-4c5db7867fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e49f04d-f2f9-46d9-b999-9adac1a82e7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f13097ee-d065-46f3-93b3-41af4b8e53f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0665ee7e-3f0b-4fe1-ad09-f2d0d822984d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9af108ba-9f86-48e8-8818-cc9ab28e3f2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698a12a4-493e-4f09-85e9-e11fdae4a928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c646e4be-2e69-4674-8939-f5ff952e6d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6d9862-d9b3-4fde-b62f-bee325635c8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceb9d2b6-e893-4566-ac8d-44c097f298d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d2c622-6459-4e6c-bbc3-c38ff9f527e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b45ca6e3-3376-4a8f-9211-b333d5c473f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99847996-deca-4df3-b842-0b2f9e187387</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>169f8b93-d485-4924-aa50-f570e07a483f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da803449-53a8-4d5f-8ec5-c41be41e2fd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47528c01-143d-4ca1-a6f8-5050a7d775a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36fe33c4-3691-499a-bfe6-35b337016e2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e81bb8-0d1f-4a8a-97ff-f2f6a9aa6818</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4023b7ed-909c-4a4b-beef-a3b7247fb488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0601450-b302-4197-8d41-9054556af021</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ae883f-8d05-4537-bcf4-0492ce73d514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>042e55dd-3d82-40e2-b5d3-ef5f41272c2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8415121e-e8d9-4b3e-8e0e-bdb1fbf5cacc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3106b2a-a7de-4886-8947-54dfd5af4b2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21820a8-eeae-4cda-93db-635aba0c0bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28f1a0c2-900c-4dae-ad6b-f21639d0b2f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e310205e-1d66-431c-86eb-15973ef4b741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06af43f5-593a-4d6d-a57a-a3cd97f337da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d393c01-8241-43d2-9809-8b2a2f1a50d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be2a6d2e-fc9d-4862-9b49-f3dafe4ef0d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b62116c-cca5-4334-bd37-dc0157c1ad1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d32fad-c641-4e17-9931-a0283099d41b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72eef85-a5a6-433e-b1fc-d3fab60ce3a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a35de837-1716-4fa5-9a6f-ddb3753b3674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e02cee-44bd-4958-ae86-e7ba7e5508ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e14cc692-e296-4352-8bd0-b200be07e490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e455cfd7-c11a-4d15-bba0-d6467b4dd956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c63c451-8883-4327-8918-37ce6be615cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c952084d-fdd3-401a-9bef-8fa8f1731ed2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4122edd1-fad9-4f38-9479-77c764e59266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6277fbf-363c-4efe-b7cc-e423f74135b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26034611-d58c-4dfa-a18e-7f300d95b9cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ab07094-f59b-4ff0-b25b-552dafc71be3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0919500-0f67-48ae-81fa-a3564287af75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f8dd6de-6870-4155-8de1-236709aaffdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a66905a-58b4-40bd-8373-20617ca3a41d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47cb9dab-3988-44f7-b2ed-d9bb2ac13aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbc84ea-38da-4818-afea-bbf2815fcae6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fc04445-4588-4f7c-aa2b-4c28ecbb3d62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 1/01-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1488665-b469-48ad-b256-dfbd50dacb8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83474069-e750-432e-aa10-f2408e5a3746</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87c9aeda-3706-4c2d-9ef1-ce1721870707</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>9d378a58-b53f-4687-9eff-8e530dbc86b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>358c7850-ce00-4039-8a6e-f29a3624c1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>e9d01703-bbf3-47da-bee2-3ee54840168b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>51bd8172-600d-4109-bf4e-10fc8f173026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>97233486-3d30-4f80-9c3f-4eca68f26960</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>9b8a650d-bb05-4fcc-843b-af381b59f908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>4be4ef13-d3da-4fe6-bb22-84858b6d9782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc347f78-0f7e-4a1e-bf71-0f1da30131fc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>f48fe2cf-ca0d-497f-8c9d-61099435bf13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18a9ce67-e064-4664-90e3-2e0df48ccbb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-02-Transaction-AppPending-InputCorporate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b355e5da-b1e3-4d01-8c9e-5389dc0d2857</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5efdcc39-093f-4b14-981f-6e99c092d1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>156881f5-f8d7-428a-bb2d-6e886b9029ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad49aea-733b-4251-8619-c4c858213f08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc8a210-f1e1-480d-960a-343e61f6aa34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6226c190-bda5-4870-98a8-c5cfc2bd19a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>395e4749-a0a4-4c60-9842-4bc5e1a65a5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e96d66cd-f6b4-4a73-87ef-8a706b9a0b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ac86ecd-613d-4bc1-8cb5-752683e3aa1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d540dfa6-98ed-4ccd-ac9f-0f87aca692d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3739a319-8568-455d-80e8-04528b4e39a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78e1a97-5bca-45af-bce4-3b16101789fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>338b21d8-c1bd-40d2-973f-6672a8514c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c2ec79-8525-4936-83a1-af95f41493e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cc6250-73f5-40f6-9ec2-876f058f489d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20485d5-c524-438c-98f3-d93cc6d75fe2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54a49240-fd6b-43c5-a4c1-7e76ced1f69d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be77464b-00cd-4425-9af4-a21c6e9659a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9327ff86-9a76-403e-be79-eec167b33661</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>640a7e53-c077-4b67-a7bd-ce95904e188c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eac3cb9-afa7-4f81-a894-6227d2b9bb1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4207ea38-a830-4729-8665-982a525224b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75054808-9c25-4bc3-9439-00a3d0230b40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4f5031f-11cf-4e89-bd90-5190e7adc907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f48c71d2-50c8-40af-8c63-9f9ab0ada6e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a84a740-d44e-4fcc-99de-f6b1d01608fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56e2739d-7948-42ee-8b36-0534a8bf6437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80ca63e8-c0cb-4ba8-95db-2b5cc4f4bce0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe6081a-6dbe-42de-922f-8e222ea25a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8862c000-fc95-4045-a346-e617c8715359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8604fb4a-1eff-494d-90e1-c05c1f2abe09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e5e909-65c1-4fb8-ae7d-b998d6b7dcf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f30f123-85e0-46fa-93cc-ed1974a073f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0ff74d9-70bc-4f98-b99e-e73867fbc9a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad27cc4-acc3-4f7e-b055-23bbf7871939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d753b0f8-b8b2-4358-84d2-baef8c46e95c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bc907c-f7df-43f5-b3ab-f6f98a81a8ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f99c77b0-3b64-44ad-9a85-dd35a1206147</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80de5320-b18a-4052-913f-659edff399ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e693c37a-2d52-4f91-9eb4-ed4e8253a7cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60ef0c86-59eb-4080-9407-9b67f8f4c013</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0466905a-4622-4413-96c8-00f344fc9137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c53bce4-916a-4ea6-94d2-09641d00433d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e5755f2-027c-4a1c-9447-119b177db9c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbd5040-4850-40b2-bb5e-88d632306e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f5af81-d3f3-47ce-a4f0-29594bb4dedb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c221a5f3-af03-4c41-bbaf-acfdc2eb2a36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43a3b8ed-79f7-4ea7-83c7-77e65409a741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c5a6c60-92d0-4846-bd30-6bd156f091d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20ea7253-bb50-4d22-9526-2036ff90ab42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bffaee33-c198-461d-bfa3-a3f5b733b6fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9a45c5d-fadf-4b86-a61a-337326eff9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0c839f6-1809-40b2-807d-2a3865122b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cead8c6-f6bb-4260-9d1c-99e6892bc479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8adcd7ac-7496-486b-beee-7c6b37e7f60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36d90b40-aeb5-4ecf-967b-0c9cc88a0657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e209671-56cf-4314-9c64-39e3e7923aa4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfdfb507-9cae-457e-882f-7ceba61ad594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc5d5b0-b69e-49a3-9180-7e06cadf487b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bbd56be-ac0f-4720-96ef-9fe1bda8cace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e57b2e7-6940-4e1c-bb2a-e2b74bd245d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edbbe942-0e50-4ac7-bb33-9451b2c35ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64a31581-f3f6-448b-84f2-7e088a45a7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b41f45e-5dae-40c1-8c90-47234067a3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>149b19ec-7c89-4218-90c9-a429a6625142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91264f81-9a9b-451c-8c5a-13ef3ce61c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8f4f6de-b256-4cab-8012-4718a0afde82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70915175-4f4f-4b90-9af7-f6d81b52a72b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44830299-105a-4c2f-bd63-b9e286437460</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>337a85fc-59c4-43ea-99e9-7f6c7f005647</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5421850b-b86d-4ca4-b87f-da958b0ece98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3be46574-d22e-4136-a68e-d01fc51ddae7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d2725059-a837-4300-902c-3464b902c4b2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>f5c275e7-e354-49b9-a24b-05e9c329421a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>f1cee303-3186-4e49-9439-ab05054737b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>30550438-87a7-48f8-a2e8-6718722237fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>2e304e44-c008-4c4f-a0cf-00d7f015fc62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>6ea45026-c48c-41df-b57d-6ea373db049c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>c2ff8504-32e2-4b4e-8afc-6a7a297aa57b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>c098cccd-49fd-4c0e-bcfc-33528470065f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d2725059-a837-4300-902c-3464b902c4b2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>c211bc21-3fcc-48c2-a0f3-7c08b39bc37c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4078d49d-bb3f-4023-abb7-f7d8f238e9b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-02-Transaction-AppPending-InputCorporate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25e35ab1-9be8-4a78-b203-cb87a4f5d7ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67d306dd-e411-476f-b837-9000f91c1016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29448307-970d-409c-a3ea-8fcf0320f664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6138a7f-7361-4529-a736-06d7d6a55331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceeacdb0-f0ff-4466-9c5d-62b300b27e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4e6757-7ac1-4bbf-9c58-117689ccd363</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a8ef93d-6547-4926-a7be-f20ad1a8f6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f95f3d-4613-424f-8bf9-51736aa4fe92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4b3b015-5516-44cc-bfd2-063118ddd7da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7def924a-1ff8-4378-896c-7a89d8917bfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f966e42-2523-4ede-a6ac-3558533d3306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e65453cb-d9dd-47f3-8f79-692d27fd2d2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58e1c0d4-a0f1-449a-84aa-d85b393f554f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b388fb-5730-479b-a4a0-136b403b94d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7265b77-2956-42c9-9fa6-36651e04e98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ded7187-b270-4d8f-9dc4-1e3f0cd3ccfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12c9e7e0-f65e-4d02-859e-2f78a13564f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>725baa43-2efc-431a-af2d-453a1007bd20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1438749-36c2-4193-94b9-8f055d15033e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a219591-7bcb-42bb-ba0f-5b536ae9882c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1099f1da-076e-4300-a17e-722c97e42409</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fed10fb-95fc-4423-b62d-928595b08a34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7774b39-77dc-42ca-aca2-7187d0a49443</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b60def-be1f-49c8-9e01-a66e1b1efc04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52196024-5a2a-4d53-9edc-59cbb7074a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2b2b9e3-edd9-4de4-a494-ddc10eaa7263</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef91c8e5-e284-411c-9b57-acb133e629d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a2717d-2258-4a21-ba90-e226fff74182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5f46c2-13b6-46cc-9f9a-353b11261054</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>499d3672-b7f0-493b-803f-7908d4de0547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a722afb1-9ec6-42a7-bdbd-ca5335ba3672</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc56c64e-aff0-4bbc-a75b-088c71785a1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e52920e-cc7d-4620-a040-1685febb4843</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4df9bc75-2746-471e-8a89-a4d88daf1995</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dfcf372-fe04-407b-a04b-d192c93b6ea6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a749a59b-6cc3-4911-b2ae-d03fe077c4b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e0d0ee2-0700-4fa4-b666-2241781363ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab7988f5-6aa0-44a7-afe8-68194be202d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c095f78d-d130-4be9-975e-1342c04934a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357499da-b207-4953-a325-282c805bcd25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa141ef3-aac3-48b2-bda7-88177dddb3d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0712d15f-7d3b-4151-a2f1-bd1dd09df0a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61bf27b-f8f8-457e-ab5d-21a78819b155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae9d3b7b-e0d9-4ea7-ae4d-1f73a1c60272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce5858f-8bc2-473c-8bb2-9745d20f5de9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a5b30e-3433-4ef2-9a82-fe52fc3e5dee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a867da-16e2-4db5-9746-a2a2ae98387e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1392c9a-fbe0-42b1-8fc6-11ad8b014654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b1b50c-d04a-4ce1-828b-05bbdfa25359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ee16fe9-d276-419f-87c4-fe7aa759f157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba8fac5-0f7c-414b-8a06-65d73af902b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0944b87-b4cd-4fdb-9df1-fa6b7882d121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6a55a6e-8fb4-458e-a343-57760bdfd9e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a02853-1f50-45d5-a223-3f12bc13e74d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88dea1a4-8b9c-47ed-adbc-292fc61e6dc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468118a5-f23d-4b06-8fd7-8b2ce94db6c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98e1742d-e150-43ef-af06-1eca79a6e66b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d30233-f4f2-426e-9a35-02c35e23ff2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a336df-e0b8-4e96-a68b-113122f7a622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4206ff4-0cad-4129-b32b-5231136bd557</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3432d35d-6d17-4014-ab03-a88e7483ad51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c323f7c-d318-4fe4-87eb-27dc3fe4b10d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0fea0e-d138-4d6d-b950-d80c118db5b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4141c1e9-b36f-43e0-84ef-63ba77596672</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6455dcc-2cdd-4f29-90d0-f9dd5a5829e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d13bd5-3868-44a3-9f55-fa0b80e2b20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f89644-7181-4780-82dd-efc8dbb4e952</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>704a77b8-e585-4671-9d0f-ae7c0f7e7775</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed9906c-3ed7-4db0-b18d-2a4a188983d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c21bd257-4d03-4bad-ba50-f644c9d79e2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ece2684-50c3-4cbb-99a9-384033a9fad8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5d837d12-ae65-4eec-9038-aa0c26558417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2f68d10b-fe12-4198-b860-53d0aa221978</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>e5859086-4ccb-4a34-90e2-972df6ab8f01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>5cb91d9d-156b-4e69-9f86-a7d6b1f49d5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>c5fe3b95-179d-4d4e-b1c8-2911ad9ac0f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>6e7069f8-d137-4c0d-bef7-67e46f27e8ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>1fae39e6-63bb-4a28-982b-b2de08b1cfb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>5c83456d-9a94-4653-88bf-1ac0849a27b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>f2f2c473-bb77-463c-9e83-ade752071bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2f68d10b-fe12-4198-b860-53d0aa221978</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>2e814dbd-2dcc-4d11-999c-cde9f1318421</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>127f63cf-eca3-4fd4-b525-dfc5aab20f0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-02-Transaction-AppPending-InputCorporate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0b6d90-dec8-4e83-bd37-5a4c78e38767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37554057-993f-4e7a-868a-6ad3263d1643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8360c0a-7284-4383-a839-5b6890f71d2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1706eac-8c97-4527-9bed-055febb8d3c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>117ce987-98e0-4da7-9238-887f512346cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a02ac06-3134-4404-bb34-4e9abc73c55c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65902f3-9bd9-40c7-a9a2-90096414af53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb8977e-6aca-4b96-924c-2193a9924d3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>155ed95b-62fc-4dfd-b2e3-f9dcd09baa8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>722cc434-f141-461d-bc33-69c2d961331a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9626a10-f63c-46c5-b9ce-979da8017c1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5f2fd8-ce5d-4cc0-95fc-14e3ddd55ef2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4891799-6a5e-4aa5-aaf7-fa67be4e0dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea570f4c-96b3-437e-a7ec-2f9db8f0d244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a169830-c7f3-4860-b6a3-69e45c79457d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b0f6347-2eff-4a39-acbe-67be4571d4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>946d5c7e-ceeb-49c3-9a28-94e0c156fe19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24599603-00a9-4de7-8f2b-8379fb7d6702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7dde7a-3f0a-4ed0-8d8c-553ddb734a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f647591-e3d5-40d1-ade8-2432a405ca35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2607fd8e-a455-403d-bdc9-bedef1deb9a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7ad87cc-426d-47f7-b77f-6c634c5415ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f18dbd27-7ef5-4cd1-b4ab-fad610562278</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c8f83d-82db-432c-83a9-00775650c73a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b73519-3d08-4777-8596-aee9831ebeaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e939c74-5900-4eb4-9ee6-8810a61ab54f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d43c72e-0ad4-4cbe-8216-37447e446348</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f073ba8c-50d8-40b0-9aca-c6cccbdf80ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ce0a392-6e47-4b78-80b8-5d03a5894776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8abd981-6e39-44ec-91f0-6ec3a3f077c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>624f81e6-8db4-4c46-b9e8-c3f374512452</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea45c88a-1df0-4a08-a50c-32755b718638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9aad172-05ff-44bc-9c32-5d21dd4d84e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf614120-c438-412c-ab0a-bc057f26c70d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ee3e3f-c19e-440f-8df5-ae9c9aceaeff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d1bf2b0-2984-4e3c-948e-6e8b90c9653e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8be87e2-e84d-4643-bd99-d94c9669e88e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca009b84-917c-44e3-b3cd-be1b0307618b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f35c35a-7070-43b6-af5b-21a3725fd8f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bceaf461-3868-42ba-87a9-d6dfb7c2df77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34983fdc-c0cc-4b3d-99ba-70e8678cbdfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>595bda0d-2e2b-449c-b0fc-417b8b00b2bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6654c8c2-af89-4212-bb7d-99b106d6ebd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55c7449b-ab76-49ae-821c-84f0126015ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d326e73d-2566-4426-b841-de9477564d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b8054af-6da2-411d-92bb-6c88c5bcf76b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53c4743a-5b77-497a-b737-e0b935926de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9e5ea7-159d-46ad-b221-91f4a765fb8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb1ba0fa-e926-48ab-b768-7840c14a53ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f48a52-f843-42e9-952f-212c3aa2e5ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64fc9532-cbd4-44db-9750-0fc802f15d00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e887c94-3463-42f8-b305-766bb662c182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a43b33-552e-4646-bb2c-f86540900fda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a83f3c9-6f56-4c84-bf02-8ed3b40b918b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c35aadd-403d-43d0-9df8-e9197196aebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe308b2-a2e6-4c21-b23f-b951ae5ca2f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18e2a4bc-c37b-41b6-8afe-fb22ca171784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68340dd-e41d-48da-a052-eff6f1262732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd77b4e3-0e72-4872-a09f-576d90a36569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1b4935c-ca6c-4959-b4b6-b298d15e52da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39781da4-d79e-4713-9d38-f92213999161</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff13c65d-ee2f-4504-889c-bfaa0ee2f884</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6470b28c-b8cc-4fd5-a7b4-d98d65ecf263</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e195f877-fd44-4794-aada-2230be6e1122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70b7284d-a74e-4268-aec2-a5297c909ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95bbfb81-e1cd-4de9-8bec-0aa76dd6d176</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc9128e1-0d88-4a53-855c-f1e3a684af40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57584752-da3e-42ef-b920-ef7cbea77d9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae2f6922-e6a7-47b5-b9ba-a86202c78e7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14555244-a67f-47dc-86c5-139894dfab98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04470682-28da-41ce-970a-ff180691cdb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
