<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3bdb1f8f-65d0-4354-89d8-31ab3e701f88</testSuiteGuid>
   <testCaseLink>
      <guid>55196ad7-a0d6-42c9-b9bf-9d916e726ca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>492f8582-fef4-4b9b-a99e-e43d88c86137</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>e5859086-4ccb-4a34-90e2-972df6ab8f01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>5cb91d9d-156b-4e69-9f86-a7d6b1f49d5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>c5fe3b95-179d-4d4e-b1c8-2911ad9ac0f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>6e7069f8-d137-4c0d-bef7-67e46f27e8ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>1fae39e6-63bb-4a28-982b-b2de08b1cfb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>5c83456d-9a94-4653-88bf-1ac0849a27b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>f2f2c473-bb77-463c-9e83-ade752071bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>492f8582-fef4-4b9b-a99e-e43d88c86137</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>2e814dbd-2dcc-4d11-999c-cde9f1318421</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa982f22-cff7-43f2-9aa4-fadc59944e6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-02-Transaction-AppPending-InputCorporate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0b6d90-dec8-4e83-bd37-5a4c78e38767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37554057-993f-4e7a-868a-6ad3263d1643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8360c0a-7284-4383-a839-5b6890f71d2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1706eac-8c97-4527-9bed-055febb8d3c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>117ce987-98e0-4da7-9238-887f512346cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a02ac06-3134-4404-bb34-4e9abc73c55c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b65902f3-9bd9-40c7-a9a2-90096414af53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb8977e-6aca-4b96-924c-2193a9924d3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>155ed95b-62fc-4dfd-b2e3-f9dcd09baa8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>722cc434-f141-461d-bc33-69c2d961331a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9626a10-f63c-46c5-b9ce-979da8017c1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5f2fd8-ce5d-4cc0-95fc-14e3ddd55ef2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4891799-6a5e-4aa5-aaf7-fa67be4e0dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea570f4c-96b3-437e-a7ec-2f9db8f0d244</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a169830-c7f3-4860-b6a3-69e45c79457d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b0f6347-2eff-4a39-acbe-67be4571d4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>946d5c7e-ceeb-49c3-9a28-94e0c156fe19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24599603-00a9-4de7-8f2b-8379fb7d6702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7dde7a-3f0a-4ed0-8d8c-553ddb734a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f647591-e3d5-40d1-ade8-2432a405ca35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2607fd8e-a455-403d-bdc9-bedef1deb9a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7ad87cc-426d-47f7-b77f-6c634c5415ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6940c08-fc60-4939-8379-49ec8c1ba91e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c8f83d-82db-432c-83a9-00775650c73a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b73519-3d08-4777-8596-aee9831ebeaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e939c74-5900-4eb4-9ee6-8810a61ab54f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d43c72e-0ad4-4cbe-8216-37447e446348</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f073ba8c-50d8-40b0-9aca-c6cccbdf80ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ce0a392-6e47-4b78-80b8-5d03a5894776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8abd981-6e39-44ec-91f0-6ec3a3f077c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>624f81e6-8db4-4c46-b9e8-c3f374512452</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea45c88a-1df0-4a08-a50c-32755b718638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9aad172-05ff-44bc-9c32-5d21dd4d84e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>182c6365-c534-459a-b689-c795ae19b3d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ee3e3f-c19e-440f-8df5-ae9c9aceaeff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d1bf2b0-2984-4e3c-948e-6e8b90c9653e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8be87e2-e84d-4643-bd99-d94c9669e88e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca009b84-917c-44e3-b3cd-be1b0307618b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f35c35a-7070-43b6-af5b-21a3725fd8f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bceaf461-3868-42ba-87a9-d6dfb7c2df77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34983fdc-c0cc-4b3d-99ba-70e8678cbdfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>595bda0d-2e2b-449c-b0fc-417b8b00b2bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6654c8c2-af89-4212-bb7d-99b106d6ebd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55c7449b-ab76-49ae-821c-84f0126015ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d326e73d-2566-4426-b841-de9477564d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b8054af-6da2-411d-92bb-6c88c5bcf76b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53c4743a-5b77-497a-b737-e0b935926de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9e5ea7-159d-46ad-b221-91f4a765fb8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb1ba0fa-e926-48ab-b768-7840c14a53ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f48a52-f843-42e9-952f-212c3aa2e5ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64fc9532-cbd4-44db-9750-0fc802f15d00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e887c94-3463-42f8-b305-766bb662c182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a43b33-552e-4646-bb2c-f86540900fda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a83f3c9-6f56-4c84-bf02-8ed3b40b918b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c35aadd-403d-43d0-9df8-e9197196aebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe308b2-a2e6-4c21-b23f-b951ae5ca2f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18e2a4bc-c37b-41b6-8afe-fb22ca171784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68340dd-e41d-48da-a052-eff6f1262732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd77b4e3-0e72-4872-a09f-576d90a36569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1b4935c-ca6c-4959-b4b6-b298d15e52da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39781da4-d79e-4713-9d38-f92213999161</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff13c65d-ee2f-4504-889c-bfaa0ee2f884</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6470b28c-b8cc-4fd5-a7b4-d98d65ecf263</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e195f877-fd44-4794-aada-2230be6e1122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70b7284d-a74e-4268-aec2-a5297c909ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95bbfb81-e1cd-4de9-8bec-0aa76dd6d176</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc9128e1-0d88-4a53-855c-f1e3a684af40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c1edc50-e2b4-41fc-9821-345f1a3a1b90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae2f6922-e6a7-47b5-b9ba-a86202c78e7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14555244-a67f-47dc-86c5-139894dfab98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58edba22-eb0e-4bb5-8ebc-640daa431482</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 4/04-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
