<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath_dynamic</name>
   <tag></tag>
   <elementGuidId>c3e1ac66-ae44-42bf-8049-fae134a9be5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
