<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Capture_</name>
   <tag></tag>
   <elementGuidId>42fd31b9-434b-4b29-b1b7-5887dd602466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Capture' or . = 'Capture')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='modal-body']/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8fb904b9-7b56-48f2-965e-c793213e6b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capture</value>
      <webElementGuid>975787e6-6f37-48d2-b044-7cd173cbaac7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
