<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>88119e20-3809-464d-a4f2-1d0f6bb24688</testSuiteGuid>
   <testCaseLink>
      <guid>53fe6709-d99f-430c-87f8-d78ae16acb96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>f5c275e7-e354-49b9-a24b-05e9c329421a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>f1cee303-3186-4e49-9439-ab05054737b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>30550438-87a7-48f8-a2e8-6718722237fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>2e304e44-c008-4c4f-a0cf-00d7f015fc62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>6ea45026-c48c-41df-b57d-6ea373db049c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>c2ff8504-32e2-4b4e-8afc-6a7a297aa57b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>c098cccd-49fd-4c0e-bcfc-33528470065f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0fcacfb2-3c5c-4428-95dd-cadc550e0c5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>c211bc21-3fcc-48c2-a0f3-7c08b39bc37c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a90edfd9-7f1d-4e0c-862c-d85ea4dc37cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-02-Transaction-AppPending-InputCorporate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25e35ab1-9be8-4a78-b203-cb87a4f5d7ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67d306dd-e411-476f-b837-9000f91c1016</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29448307-970d-409c-a3ea-8fcf0320f664</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6138a7f-7361-4529-a736-06d7d6a55331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceeacdb0-f0ff-4466-9c5d-62b300b27e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4e6757-7ac1-4bbf-9c58-117689ccd363</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a8ef93d-6547-4926-a7be-f20ad1a8f6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f95f3d-4613-424f-8bf9-51736aa4fe92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4b3b015-5516-44cc-bfd2-063118ddd7da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7def924a-1ff8-4378-896c-7a89d8917bfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f966e42-2523-4ede-a6ac-3558533d3306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e65453cb-d9dd-47f3-8f79-692d27fd2d2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58e1c0d4-a0f1-449a-84aa-d85b393f554f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b388fb-5730-479b-a4a0-136b403b94d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7265b77-2956-42c9-9fa6-36651e04e98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ded7187-b270-4d8f-9dc4-1e3f0cd3ccfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12c9e7e0-f65e-4d02-859e-2f78a13564f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>725baa43-2efc-431a-af2d-453a1007bd20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1438749-36c2-4193-94b9-8f055d15033e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a219591-7bcb-42bb-ba0f-5b536ae9882c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1099f1da-076e-4300-a17e-722c97e42409</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fed10fb-95fc-4423-b62d-928595b08a34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd1f5906-387e-4ee8-8692-7441b15aece0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b60def-be1f-49c8-9e01-a66e1b1efc04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52196024-5a2a-4d53-9edc-59cbb7074a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2b2b9e3-edd9-4de4-a494-ddc10eaa7263</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef91c8e5-e284-411c-9b57-acb133e629d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97a2717d-2258-4a21-ba90-e226fff74182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5f46c2-13b6-46cc-9f9a-353b11261054</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>499d3672-b7f0-493b-803f-7908d4de0547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a722afb1-9ec6-42a7-bdbd-ca5335ba3672</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc56c64e-aff0-4bbc-a75b-088c71785a1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e52920e-cc7d-4620-a040-1685febb4843</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68a427df-1cf9-4c6b-a8f6-24eeafb147de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dfcf372-fe04-407b-a04b-d192c93b6ea6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a749a59b-6cc3-4911-b2ae-d03fe077c4b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e0d0ee2-0700-4fa4-b666-2241781363ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab7988f5-6aa0-44a7-afe8-68194be202d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c095f78d-d130-4be9-975e-1342c04934a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357499da-b207-4953-a325-282c805bcd25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa141ef3-aac3-48b2-bda7-88177dddb3d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0712d15f-7d3b-4151-a2f1-bd1dd09df0a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61bf27b-f8f8-457e-ab5d-21a78819b155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae9d3b7b-e0d9-4ea7-ae4d-1f73a1c60272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce5858f-8bc2-473c-8bb2-9745d20f5de9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a5b30e-3433-4ef2-9a82-fe52fc3e5dee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a867da-16e2-4db5-9746-a2a2ae98387e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1392c9a-fbe0-42b1-8fc6-11ad8b014654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b1b50c-d04a-4ce1-828b-05bbdfa25359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ee16fe9-d276-419f-87c4-fe7aa759f157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba8fac5-0f7c-414b-8a06-65d73af902b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0944b87-b4cd-4fdb-9df1-fa6b7882d121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6a55a6e-8fb4-458e-a343-57760bdfd9e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a02853-1f50-45d5-a223-3f12bc13e74d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88dea1a4-8b9c-47ed-adbc-292fc61e6dc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468118a5-f23d-4b06-8fd7-8b2ce94db6c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98e1742d-e150-43ef-af06-1eca79a6e66b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d30233-f4f2-426e-9a35-02c35e23ff2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a336df-e0b8-4e96-a68b-113122f7a622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4206ff4-0cad-4129-b32b-5231136bd557</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3432d35d-6d17-4014-ab03-a88e7483ad51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c323f7c-d318-4fe4-87eb-27dc3fe4b10d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0fea0e-d138-4d6d-b950-d80c118db5b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4141c1e9-b36f-43e0-84ef-63ba77596672</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6455dcc-2cdd-4f29-90d0-f9dd5a5829e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d13bd5-3868-44a3-9f55-fa0b80e2b20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f89644-7181-4780-82dd-efc8dbb4e952</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0110e139-ecbb-47cc-9b53-021df3873bd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed9906c-3ed7-4db0-b18d-2a4a188983d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c21bd257-4d03-4bad-ba50-f644c9d79e2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7518b20a-09e7-494b-87bf-022a767a6b6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 3/03-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
