<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account No. 10 Digit_form-control ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>fa9acfd1-e01a-4313-b942-045969f6132b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.ng-star-inserted > div.col-md-6.form-group > div.d-flex.input-container > input.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'number' and @formcontrolname = 'accountNoBca']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>927f3f4f-e4a2-460b-9404-ca8b71711755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>39bcf388-91ce-46f4-b1b9-4db72ec8485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>0000000000</value>
      <webElementGuid>d82e81ff-c239-4f7f-a402-21aad2ca0d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0f6c2a13-9c68-4f97-8ef8-15d7eca8bc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9a3d9ee1-2b8f-4598-8d10-a60701308ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>accountNoBca</value>
      <webElementGuid>81f5830d-5853-4288-a03f-aed4cdc19fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6070cae9-1322-4ce1-a6f9-392c04b97c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion_financial&quot;)/div[@class=&quot;card mb-0 rounded-0&quot;]/div[@id=&quot;siup-document&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-6 form-group&quot;]/div[@class=&quot;d-flex input-container&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>f839311c-9502-41b6-b3d9-ea296c0459ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[20]</value>
      <webElementGuid>356512b0-9d2e-45da-990a-12feda5d3cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siup-document']/div/form/div/div[3]/div/input</value>
      <webElementGuid>24810c86-ed3b-4433-9109-103594b94371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/input</value>
      <webElementGuid>aaaf96c2-17ed-425d-bb48-16ac57a66336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>67b13947-3358-42ed-a390-56b3bf7f56b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
