<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>other_bank</name>
   <tag></tag>
   <elementGuidId>cc0499bd-e589-4ae3-9d92-8e0c3969dff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.ng-star-inserted > div.col-md-6.form-group > div.d-flex.input-container > input.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'otherBank']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ng-select</value>
      <webElementGuid>a4685d5b-a50c-4d2d-a28a-cb421a03b02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>otherBank</value>
      <webElementGuid>d2520999-d1f3-4a95-b4ff-a7449c55e011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a3c8638e-9342-4982-a44d-fb92d7b2ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion_financial&quot;)/div[@class=&quot;card mb-0 rounded-0&quot;]/div[@id=&quot;siup-document&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-6 form-group&quot;]/div[@class=&quot;d-flex input-container&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>7fdad47e-75c8-45b6-8e15-d2ab368aa207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[19]</value>
      <webElementGuid>9f88bf3f-a66c-4fd0-b544-44e61f1be00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siup-document']/div/form/div/div[2]/div/input</value>
      <webElementGuid>42efc20f-d40b-4355-b9ee-86ccb6d6abe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form/div/div[2]/div/input</value>
      <webElementGuid>c482d4e1-93c1-4e46-ab8c-0f6b0e062041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>0ef51960-e841-4715-a238-2cb9790d89cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
