<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Warga Negara Indonesia_nationality2</name>
   <tag></tag>
   <elementGuidId>e309a80c-1f26-418f-83e9-fa43514f45c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nationality2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nationality2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffaba83c-17c9-46bd-a67b-348c178cbdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nationality2</value>
      <webElementGuid>089468e9-c52f-4617-b902-fbfadb409278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b99743e3-624b-4f76-93bc-1ebfdd18615d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>91c2c368-c5db-4e06-a7e1-719e58a2cc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>WNA</value>
      <webElementGuid>cd6a1f31-639c-4763-9ddc-4d3b730f2246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0ad1e720-4bd0-40c7-b1ad-9cfeadb84ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nationality2&quot;)</value>
      <webElementGuid>fbcd6918-344d-4b40-a9be-fd499e8a9256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nationality2']</value>
      <webElementGuid>94bd81a6-da11-4929-9014-80a9f692930e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-0']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>e73b148d-4565-48e3-b6f0-8fe9e3898e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>d4bae6fd-0f4e-44f7-961d-5f15371f0302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nationality2' and @type = 'radio']</value>
      <webElementGuid>cda3d8a1-d171-4131-b5ba-36620f43f345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
