<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kewarganegaraan_nationality1</name>
   <tag></tag>
   <elementGuidId>86b32d39-f36c-4758-bb49-2946a6b8966d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nationality1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nationality1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50013841-b79c-44b7-be76-a9fb1265f4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nationality1</value>
      <webElementGuid>4da84173-7a53-4e56-aa9d-375e81295c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>19d9d328-ce68-4625-bec2-ce8bbf43c22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationality</value>
      <webElementGuid>5f658bd5-0444-4249-b4e9-36c96f8598c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>WNI</value>
      <webElementGuid>75c04c50-ad27-432c-9067-25d5dc8be07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f26768e7-9376-4e4c-8a7f-cd375fb38134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nationality1&quot;)</value>
      <webElementGuid>7fe5cf07-7765-4531-b497-fc6c64951ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nationality1']</value>
      <webElementGuid>6f5e7ac6-e1cd-4a8c-b0fa-ed39e069b3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-0']/div/div/div/div[2]/div/input</value>
      <webElementGuid>f82ad44d-f48c-4970-8045-638d281a0295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>66ec1694-cfc5-4f46-a404-2f4e9e9e2992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nationality1' and @type = 'radio']</value>
      <webElementGuid>bd9901cd-97ef-4114-91f0-ba6026f4fe18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
