<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apakah memiliki Beneficial Owner_isHaveBO</name>
   <tag></tag>
   <elementGuidId>27c6e2a0-c6c4-498d-b22d-28eaa2e87033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isHaveBO1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isHaveBO1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bfb0632-68ad-43d7-a606-d56bf4307855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isHaveBO1</value>
      <webElementGuid>42269850-e54d-4a5d-8068-2c01453c4bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6512d962-15aa-4808-bc7b-36194bb4cd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isHaveBO</value>
      <webElementGuid>dea6c733-0256-4ce4-b2bb-08caf3615f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isHaveBO</value>
      <webElementGuid>8d7fb6e6-ba5f-4cea-97c9-916774b561b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>2361bf64-7685-4728-86f6-29fb0211412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isHaveBO1&quot;)</value>
      <webElementGuid>cd86f81b-6688-4329-9d08-bcef49f302c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isHaveBO1']</value>
      <webElementGuid>ba36b382-86d0-4485-9f80-231a9c22bf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionBO']/form/div/div/div[2]/div/input</value>
      <webElementGuid>37d206bd-0b65-4f8c-af3d-41302e0db5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bcaf-beneficial-owner/div/div/form/div/div/div[2]/div/input</value>
      <webElementGuid>02ebc308-7b3b-40c3-95df-f4d9ad9c46cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'isHaveBO1' and @type = 'radio' and @name = 'isHaveBO']</value>
      <webElementGuid>9cdc4310-1017-44a6-838b-97e2ed6d3e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
