<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ya_isHaveBO</name>
   <tag></tag>
   <elementGuidId>56887464-8698-4ff5-96fc-04d1a8f41ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isHaveBO2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isHaveBO2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>798cba97-7414-46dc-b214-96cdb2a224ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isHaveBO2</value>
      <webElementGuid>9ee8664d-c029-4881-9496-7cd6b1cee92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>527f8588-2f05-4909-9b41-5a736f1d33c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isHaveBO</value>
      <webElementGuid>8eef7f11-f2c8-4de4-bd59-c7b93bf689af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isHaveBO</value>
      <webElementGuid>ecb56116-6c3d-47d3-942c-5852ae9a49f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>b75861ce-333b-4264-bbf6-e6fee9029374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isHaveBO2&quot;)</value>
      <webElementGuid>fb1f817d-b120-4b66-9a3c-cc40535df7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isHaveBO2']</value>
      <webElementGuid>099fc4f5-69ca-403f-b313-bd19964ae201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionBO']/form/div/div/div[2]/div[2]/input</value>
      <webElementGuid>8abf7599-0135-49ff-a97f-d8523e4e54a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[2]/input</value>
      <webElementGuid>8dc98405-cbfc-477e-9822-684e25d8820f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'isHaveBO2' and @type = 'radio' and @name = 'isHaveBO']</value>
      <webElementGuid>e9e41c99-9641-446b-a5f2-fe9c103bce72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
