<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6b7074d5-5d0a-4e6b-bf89-3000806a5ef9</testSuiteGuid>
   <testCaseLink>
      <guid>4cd58e8c-429b-4761-b671-10026d4a6bab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-01-Transaction-AppBaru-InisiasiKonsumenBaru</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5f7dc0bc-c3b5-4a64-befb-354bd1922899</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/NPWPData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Berlaku</value>
         <variableId>9d378a58-b53f-4687-9eff-8e530dbc86b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Berlaku</value>
         <variableId>358c7850-ce00-4039-8a6e-f29a3624c1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Inprogress</value>
         <variableId>e9d01703-bbf3-47da-bee2-3ee54840168b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Company_Name_Inprogress</value>
         <variableId>51bd8172-600d-4109-bf4e-10fc8f173026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Done_Tidak_Berlaku</value>
         <variableId>97233486-3d30-4f80-9c3f-4eca68f26960</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_tidak_berlaku</value>
         <variableId>9b8a650d-bb05-4fcc-843b-af381b59f908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NPWP_Cancel</value>
         <variableId>4be4ef13-d3da-4fe6-bb22-84858b6d9782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f7dc0bc-c3b5-4a64-befb-354bd1922899</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company_name_cancel</value>
         <variableId>f48fe2cf-ca0d-497f-8c9d-61099435bf13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bcdf627-e683-4cb1-8d18-13df1a86bb16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-02-Transaction-AppPending-InputCorporate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b355e5da-b1e3-4d01-8c9e-5389dc0d2857</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5efdcc39-093f-4b14-981f-6e99c092d1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>156881f5-f8d7-428a-bb2d-6e886b9029ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad49aea-733b-4251-8619-c4c858213f08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc8a210-f1e1-480d-960a-343e61f6aa34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6226c190-bda5-4870-98a8-c5cfc2bd19a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>395e4749-a0a4-4c60-9842-4bc5e1a65a5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e96d66cd-f6b4-4a73-87ef-8a706b9a0b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ac86ecd-613d-4bc1-8cb5-752683e3aa1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d540dfa6-98ed-4ccd-ac9f-0f87aca692d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3739a319-8568-455d-80e8-04528b4e39a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78e1a97-5bca-45af-bce4-3b16101789fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>338b21d8-c1bd-40d2-973f-6672a8514c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c2ec79-8525-4936-83a1-af95f41493e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cc6250-73f5-40f6-9ec2-876f058f489d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20485d5-c524-438c-98f3-d93cc6d75fe2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54a49240-fd6b-43c5-a4c1-7e76ced1f69d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be77464b-00cd-4425-9af4-a21c6e9659a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9327ff86-9a76-403e-be79-eec167b33661</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>640a7e53-c077-4b67-a7bd-ce95904e188c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eac3cb9-afa7-4f81-a894-6227d2b9bb1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4207ea38-a830-4729-8665-982a525224b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a47ad29-7477-4522-8c27-1a6be3787a33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-03-01-Transaction-AppPending-InputData-Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4f5031f-11cf-4e89-bd90-5190e7adc907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f48c71d2-50c8-40af-8c63-9f9ab0ada6e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a84a740-d44e-4fcc-99de-f6b1d01608fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56e2739d-7948-42ee-8b36-0534a8bf6437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80ca63e8-c0cb-4ba8-95db-2b5cc4f4bce0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe6081a-6dbe-42de-922f-8e222ea25a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8862c000-fc95-4045-a346-e617c8715359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8604fb4a-1eff-494d-90e1-c05c1f2abe09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e5e909-65c1-4fb8-ae7d-b998d6b7dcf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f30f123-85e0-46fa-93cc-ed1974a073f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04a714d8-1457-4ee9-857c-d84b7e7296b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-03-02-Transaction-AppPending-InputData-Vehicle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad27cc4-acc3-4f7e-b055-23bbf7871939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d753b0f8-b8b2-4358-84d2-baef8c46e95c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bc907c-f7df-43f5-b3ab-f6f98a81a8ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f99c77b0-3b64-44ad-9a85-dd35a1206147</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80de5320-b18a-4052-913f-659edff399ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e693c37a-2d52-4f91-9eb4-ed4e8253a7cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60ef0c86-59eb-4080-9407-9b67f8f4c013</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0466905a-4622-4413-96c8-00f344fc9137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c53bce4-916a-4ea6-94d2-09641d00433d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e5755f2-027c-4a1c-9447-119b177db9c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbd5040-4850-40b2-bb5e-88d632306e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f5af81-d3f3-47ce-a4f0-29594bb4dedb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c221a5f3-af03-4c41-bbaf-acfdc2eb2a36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43a3b8ed-79f7-4ea7-83c7-77e65409a741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c5a6c60-92d0-4846-bd30-6bd156f091d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20ea7253-bb50-4d22-9526-2036ff90ab42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bffaee33-c198-461d-bfa3-a3f5b733b6fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9a45c5d-fadf-4b86-a61a-337326eff9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0c839f6-1809-40b2-807d-2a3865122b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cead8c6-f6bb-4260-9d1c-99e6892bc479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8adcd7ac-7496-486b-beee-7c6b37e7f60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36d90b40-aeb5-4ecf-967b-0c9cc88a0657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e209671-56cf-4314-9c64-39e3e7923aa4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfdfb507-9cae-457e-882f-7ceba61ad594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc5d5b0-b69e-49a3-9180-7e06cadf487b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bbd56be-ac0f-4720-96ef-9fe1bda8cace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e57b2e7-6940-4e1c-bb2a-e2b74bd245d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edbbe942-0e50-4ac7-bb33-9451b2c35ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64a31581-f3f6-448b-84f2-7e088a45a7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b41f45e-5dae-40c1-8c90-47234067a3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>149b19ec-7c89-4218-90c9-a429a6625142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91264f81-9a9b-451c-8c5a-13ef3ce61c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8f4f6de-b256-4cab-8012-4718a0afde82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d9604c9-52a3-40e0-86c3-b2cacb74f8bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-04-Transaction-InputPenyimpangan-ProcessBM</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44830299-105a-4c2f-bd63-b9e286437460</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>337a85fc-59c4-43ea-99e9-7f6c7f005647</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da801929-0d4e-4448-9902-99c0d0db43a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 4/Skenario 2/02-05-Transaction-InquiryStatus-SearchPengajuan</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
