<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_form-control ng-pristine ng-invalid is-invalid ng-touched</name>
   <tag></tag>
   <elementGuidId>61ec84a8-38f7-4562-bc43-26bdbf6f979b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-pristine.ng-invalid.is-invalid.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[40]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03930890-1d9f-4f06-b70e-1500a5403126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85925553-a824-48b2-9053-5bc34edd3c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>99cc292c-102a-4595-92c9-d09a29ee45c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid is-invalid ng-touched</value>
      <webElementGuid>391ed69f-cd4a-4bbb-9948-bbf9a6edfb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[a-zA-Z_., ]+$/</value>
      <webElementGuid>fa68e1d0-8aa5-4277-957b-76dbdb8e1d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionBO&quot;)/form[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;card mb-1 rounded-0 ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/div[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@id=&quot;tab-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 form-group&quot;]/div[@class=&quot;d-flex input-container is-invalid&quot;]/input[@class=&quot;form-control ng-pristine ng-invalid is-invalid ng-touched&quot;]</value>
      <webElementGuid>30230eaf-2e83-4ea5-a033-80dda9369984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[40]</value>
      <webElementGuid>87688cf2-f3a8-4f8e-b7f6-6e27716a67e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-0']/div/div[3]/div/div/input</value>
      <webElementGuid>310aa9e7-9afb-4c65-be99-3e60e9692416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>8d7b0dce-28a3-4d4d-8e25-9dad9d3ade04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d6173a11-dae2-49ca-8fec-17f0f8dadf62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
