<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identity No_form-control ng-untouched ng-pristine ng-valid ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>d7ff27ec-f86f-4142-a889-eac79b9da09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-pristine.ng-invalid.ng-touched > #tab-0 > div.card-body > div.row > div.col-md-6.form-group > div.d-flex.input-container > input.form-control.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[41]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0014c9a6-91a0-46cf-99be-fcc8ce0b9b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>225987f7-0013-44be-b58f-efb91d9bd40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>0000000000000000</value>
      <webElementGuid>8478d3c1-2263-4d78-b040-8731a013f46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identityNo</value>
      <webElementGuid>f50435e9-0e3d-4d5c-8718-536a58dc7d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>1a0614c5-5f50-4286-832b-8bc4b5154dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^[0-9]*$/</value>
      <webElementGuid>7514080d-18c5-4769-a9cb-7fedc1fa2350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionBO&quot;)/form[@class=&quot;ng-dirty ng-invalid ng-touched&quot;]/div[@class=&quot;card mb-1 rounded-0 ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/div[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@id=&quot;tab-0&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 form-group&quot;]/div[@class=&quot;d-flex input-container&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>3317f683-f5da-435b-bcd4-db4e54c31bbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[41]</value>
      <webElementGuid>9143f018-23d4-4ac0-8293-fc2dc3c59eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-0']/div/div[3]/div[2]/div/input</value>
      <webElementGuid>da39b5d4-0569-4c3c-8886-f4ce24844b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>79fd892e-91a1-4f3f-bf19-4876021daa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>0fa1786c-9c97-416d-bd8c-1976469df170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
