<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Insurance_inline-checkbox1</name>
   <tag></tag>
   <elementGuidId>f3ec4b45-514d-423e-9fd5-753e97be4ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inline-checkbox1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname = '${index}' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inline-checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>113fc2ac-49a9-4ff5-ba9c-0b3c542faaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>${index}</value>
      <webElementGuid>44260400-2b02-4cc2-9d1c-c0e84badf4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inline-checkbox1</value>
      <webElementGuid>bd19e8c0-2efe-4a41-8981-2d49e330b71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>83702335-b18c-4e77-883e-ccbfab21b56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ee214d42-83e5-4ce1-b1eb-f926014266a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-accordion&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-check form-check-inline radio-style&quot;]/input[@id=&quot;inline-checkbox1&quot;]</value>
      <webElementGuid>879b9551-1ce7-43dc-8711-d8ed4a228277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inline-checkbox1']</value>
      <webElementGuid>e7c4fe07-9cf0-49f8-9a8c-2c3a98ac16fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insurance-accordion']/div/div/div/div/input</value>
      <webElementGuid>892f085d-ad7c-4073-a498-9d9d52bbd130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>e3f3d9ac-e655-473c-9270-b2951c457331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inline-checkbox1' and @type = 'checkbox']</value>
      <webElementGuid>8cf7b28c-72c5-4f5a-a3b5-83fad1fe55a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
