<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provisional Payment_prepaid</name>
   <tag></tag>
   <elementGuidId>a4cb7421-9674-414d-a083-32db45c2b77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='provisionPayment10']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = '${index}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#provisionPayment10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed99ce34-1633-4e7e-a4d3-21840ed59975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>provisionPayment</value>
      <webElementGuid>c3329573-b935-4270-9c5a-5bcb9870613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f07b652-591d-4176-aeb6-b5b199fd18fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd66c054-9209-4fe4-9e2d-90fdb9dcef91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>769ef89a-46be-4245-a167-eec1c5bf40d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${index}</value>
      <webElementGuid>8fb7ef9e-19ee-4abf-95fb-f863f7dfe203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provisionPayment10&quot;)</value>
      <webElementGuid>2f590401-d080-4848-a806-f7b1763d949b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='provisionPayment10']</value>
      <webElementGuid>f0da434b-932b-4689-9d7f-d96f9af47665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-data-accordion-0']/div/div[9]/div[3]/div/div/div/input</value>
      <webElementGuid>4ba7cf9a-0b19-49e6-9e41-88cbd7a54b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/div/div/input</value>
      <webElementGuid>99ee45ed-b172-420b-91e4-71cf2d97f210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'provisionPayment10']</value>
      <webElementGuid>96719518-bf1f-40a9-a2c4-b4b57ff7ae4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
