<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Down Payment_dpNominal</name>
   <tag></tag>
   <elementGuidId>e4e24b9b-edca-4af5-866e-1609b602aff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dpNominal_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'dpNominal_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dpNominal_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf12c003-e4b2-456c-b5fa-122a1336f2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>c97ba033-00c1-497d-ad87-b74f1996df2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dpNominal</value>
      <webElementGuid>ee098ade-a784-4d12-83b7-2a8299adc3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8391094-22a0-4f8c-8e9e-258930b931ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dpNominal</value>
      <webElementGuid>c8064afb-adcd-4098-ab12-1435728dfb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>adf86773-c392-42b9-9cc8-ff59de2b2f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dpNominal_0</value>
      <webElementGuid>b581247e-0759-4abd-bfc7-021a042faa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dpNominal_0&quot;)</value>
      <webElementGuid>9d579265-5c16-4178-aa8f-4b22a59ad6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dpNominal_0']</value>
      <webElementGuid>32fd0142-39f9-4ad5-9a24-cd0c7190e04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loan-data-accordion-0']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b1a3db90-714f-4f7a-b4ba-6dbc57a390ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>367d65ba-c52e-44ff-ab5f-64e7b1bac2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dpNominal' and @id = 'dpNominal_0']</value>
      <webElementGuid>b93537b9-d093-4b6f-87b0-d538540c97b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
