<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_typekendaraan</name>
   <tag></tag>
   <elementGuidId>ed2ba2d8-3fc8-4b46-8233-1d478842489e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data-vehicle-0']/div/div[3]/div[3]/div/ng-select/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4.form-group > div.input-container.d-flex > ng-select.w-100.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-untouched.ng-pristine.ng-invalid > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735a074e-19de-464e-b6a5-b0acf0afc45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c801c4ea-4bf0-4b58-9289-b9941262f2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d7a7b13-70da-4aba-8270-512ae8ff65bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af7c7cda-256c-48d4-b7ee-bac7774bbfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b03c241-4323-4ac7-94f0-cf4183c31faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a98da232a3cf</value>
      <webElementGuid>a6998641-e86e-4954-9cb2-a72859c609e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-vehicle-0&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 form-group&quot;]/div[@class=&quot;input-container d-flex&quot;]/ng-select[@class=&quot;w-100 ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>70fa9642-f6c9-424f-87cc-3c47780fc4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>e9b597c0-3738-4bde-9531-aca724bbba1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[45]</value>
      <webElementGuid>f58b700a-bb40-44b8-b392-91e0f0149dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-vehicle-0']/div/div[3]/div[3]/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>869e3a23-bcc0-4eb3-aec8-d19beb3a0f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div/div[2]/input</value>
      <webElementGuid>bfeb6220-b857-4041-989e-a23752a20708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d498d732-8355-4aeb-8059-1ca92691fe58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
