<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) MT DIESEL 2017</name>
   <tag></tag>
   <elementGuidId>47665f1f-5e12-45f8-9270-2c1e1cf49d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-5yz7-result-8481-0' and (text() = 'Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) M/T DIESEL 2017' or . = 'Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) M/T DIESEL 2017')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-5yz7-result-8481-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-5yz7-result-8481-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) M/T DIESEL 2017</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-5yz7-result-8481-0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-5yz7-result-8481-0' and (text() = 'Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) M/T DIESEL 2017' or . = 'Unit 1 - ALL NEW HI LUX DOUBLE CABIN 2.4 G (4X4) M/T DIESEL 2017')]</value>
   </webElementXpaths>
</WebElementEntity>
