<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT</name>
   <tag></tag>
   <elementGuidId>4fbd7697-1531-45e9-bd5c-920a3bebd06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-56k7-result-v3az-0' and (text() = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT' or . = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'option' and (text() = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT' or . = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-56k7-result-v3az-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-56k7-result-v3az-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-56k7-result-v3az-0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-56k7-result-v3az-0' and (text() = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT' or . = 'Unit 1 - ALL NEW HILUX 2.4 V DOUBLE CABIN 4X4 AT')]</value>
   </webElementXpaths>
</WebElementEntity>
