<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_A1617 - Akita Prima Mobilindo - Pondok Cabe</name>
   <tag></tag>
   <elementGuidId>86245edc-4532-4188-ab24-cbd38941d998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a73a1fc1e863-0']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ng-option-label ng-star-inserted' and (contains(text(), '${index}') or contains(., '${index}'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-option-label.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b1b6689-d087-4862-8a19-a4d9131e73f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>53dd2a02-b3e4-454f-9604-16e1ea9d6c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${index}</value>
      <webElementGuid>2abd4a9b-3fe1-4047-aec2-2030daf0ca32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a73a1fc1e863-0&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>61d4d10b-db7b-4994-8118-e4c3f2498131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a73a1fc1e863-0']/span</value>
      <webElementGuid>0374bcdd-ec59-4112-a95e-17dd93244c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Cabang Dealer'])[1]/following::span[7]</value>
      <webElementGuid>cc9ade21-1144-4a34-860d-bac95c32c00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[2]/following::span[7]</value>
      <webElementGuid>ed3e7d32-f89c-4c1b-bfec-8cfa4533bbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harus diisi'])[18]/preceding::span[1]</value>
      <webElementGuid>4276f6c9-896b-4525-a84e-3373289739f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::span[1]</value>
      <webElementGuid>35a647e1-916e-4ae6-874f-d54247a162ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A1617 - Akita Prima Mobilindo - Pondok Cabe']/parent::*</value>
      <webElementGuid>04394956-6e1e-4d58-acef-703fec395e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>e9901e84-e088-4d7c-8501-b07aaff110d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'A1617 - Akita Prima Mobilindo - Pondok Cabe' or . = 'A1617 - Akita Prima Mobilindo - Pondok Cabe')]</value>
      <webElementGuid>99828d68-27b8-49ad-a37a-2e3d324e2436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
