<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary</name>
   <tag></tag>
   <elementGuidId>a92380ca-1cd3-4681-a9bc-04baab0b3e06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'ri-arrow-left-line']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-left-line</value>
      <webElementGuid>4297ac50-08ad-4197-9e19-19a3e032a6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>93836a24-55ee-48ab-b6fd-898c9e491966</webElementGuid>
   </webElementProperties>
</WebElementEntity>
